compiler:
  - clang
  - gcc
cache:
  apt: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
      - llvm-toolchain-precise
    packages:
      - clang-3.8
      - g++-6
      - gcc-6
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6" CC="gcc-6" COMPILER="g++-6"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8" COMPILER="clang++-3.8"; fi
language: cpp
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
  - ./common_lib_tests
  - ./dual_number_lib_tests
  - ./interval_lib_tests
  - ./stream_lib_tests
  - ./rkf45_lib_tests
  - ./stopwatch_ilb_tests
  
# # Use new trusty images, should yield newer compilers and packages
# sudo: required
# dist: precise
# language: cpp

# matrix:
#   include:
#     - compiler: gcc
#       addons:
#         apt:
#           sources:
#             - ubuntu-toolchain-r-test
#             - cmake
#             - cmake-data
#           packages:
#             - g++-6
#       env: COMPILER=g++-6
#     - compiler: clang
#       addons:
#         apt:
#           sources:
#             - ubuntu-toolchain-r-test
#             - llvm-toolchain-precise-3.8
#             - cmake
#             - cmake-data
#           packages:
#             - clang-3.8
#       env: COMPILER=clang++-3.8
#     - compiler: clang
#       addons:
#         apt:
#           sources:
#             - ubuntu-toolchain-r-test
#             - llvm-toolchain-precise-3.9
#             - cmake
#             - cmake-data
#           packages:
#             - clang-3.9
#       env: COMPILER=clang++-3.9
#     # - compiler: clang
#     #   addons:
#     #     apt:
#     #       sources:
#     #         - ubuntu-toolchain-r-test
#     #         - llvm-toolchain-precise-4.0
#     #       packages:
#     #         - clang-4.0
#     #   env: COMPILER=clang++-4.0

# before_install:
#   - sudo apt-get update -qq
#   - sudo apt-get install -y libopencv-dev
# script:
#   - mkdir build
#   - cd build
#   - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
#   - ./common_lib_tests
#   - ./dual_number_lib_tests
#   - ./interval_lib_tests
#   - ./stream_lib_tests
  